import 'package:flutter/material.dart';

/// Familia visual de ícono de categoría (desacoplada de IDs MeLi).
enum CategoryIconKind {
  vehiclesAccessories,
  agro,
  foodAndDrinks,
  pets,
  antiques,
  artAndStationery,
  carsAndMotorcycles,
  babies,
  beauty,
  cameras,
  phones,
  computing,
  gaming,
  construction,
  sports,
  appliances,
  electronics,
  events,
  tools,
  homeAndGarden,
  industry,
  realEstate,
  musicalInstruments,
  jewelry,
  toys,
  books,
  musicAndMovies,
  fashion,
  health,
  services,
  parties,
  other,
  generic;

  IconData get icon => switch (this) {
        CategoryIconKind.vehiclesAccessories => Icons.car_repair_outlined,
        CategoryIconKind.agro => Icons.agriculture_outlined,
        CategoryIconKind.foodAndDrinks => Icons.local_grocery_store_outlined,
        CategoryIconKind.pets => Icons.pets_outlined,
        CategoryIconKind.antiques => Icons.museum_outlined,
        CategoryIconKind.artAndStationery => Icons.palette_outlined,
        CategoryIconKind.carsAndMotorcycles => Icons.directions_car_outlined,
        CategoryIconKind.babies => Icons.child_care_outlined,
        CategoryIconKind.beauty => Icons.spa_outlined,
        CategoryIconKind.cameras => Icons.photo_camera_outlined,
        CategoryIconKind.phones => Icons.phone_android_outlined,
        CategoryIconKind.computing => Icons.computer_outlined,
        CategoryIconKind.gaming => Icons.sports_esports_outlined,
        CategoryIconKind.construction => Icons.construction_outlined,
        CategoryIconKind.sports => Icons.sports_soccer_outlined,
        CategoryIconKind.appliances => Icons.kitchen_outlined,
        CategoryIconKind.electronics => Icons.devices_other_outlined,
        CategoryIconKind.events => Icons.confirmation_number_outlined,
        CategoryIconKind.tools => Icons.handyman_outlined,
        CategoryIconKind.homeAndGarden => Icons.chair_outlined,
        CategoryIconKind.industry => Icons.business_outlined,
        CategoryIconKind.realEstate => Icons.home_work_outlined,
        CategoryIconKind.musicalInstruments => Icons.piano_outlined,
        CategoryIconKind.jewelry => Icons.watch_outlined,
        CategoryIconKind.toys => Icons.toys_outlined,
        CategoryIconKind.books => Icons.menu_book_outlined,
        CategoryIconKind.musicAndMovies => Icons.movie_outlined,
        CategoryIconKind.fashion => Icons.checkroom_outlined,
        CategoryIconKind.health => Icons.health_and_safety_outlined,
        CategoryIconKind.services => Icons.miscellaneous_services_outlined,
        CategoryIconKind.parties => Icons.celebration_outlined,
        CategoryIconKind.other || CategoryIconKind.generic =>
          Icons.category_outlined,
      };
}
